// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/smilex/smilex-admin-gin/internal/biz/auth"
	"github.com/smilex/smilex-admin-gin/internal/biz/captcha"
	permission2 "github.com/smilex/smilex-admin-gin/internal/biz/permission"
	role2 "github.com/smilex/smilex-admin-gin/internal/biz/role"
	user2 "github.com/smilex/smilex-admin-gin/internal/biz/user"
	"github.com/smilex/smilex-admin-gin/internal/data"
	"github.com/smilex/smilex-admin-gin/internal/data/permission"
	"github.com/smilex/smilex-admin-gin/internal/data/role"
	"github.com/smilex/smilex-admin-gin/internal/data/user"
	"github.com/smilex/smilex-admin-gin/internal/server"
	auth2 "github.com/smilex/smilex-admin-gin/internal/service/auth"
	permission3 "github.com/smilex/smilex-admin-gin/internal/service/permission"
	role3 "github.com/smilex/smilex-admin-gin/internal/service/role"
	user3 "github.com/smilex/smilex-admin-gin/internal/service/user"
)

// Injectors from wire.go:

// wireApp 由 wire 生成
func wireApp() (*server.HTTPServer, func(), error) {
	bootstrap, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	repo := user.NewRepo(dataData)
	permissionRepo := permission.NewRepo(dataData)
	tokenIssuer := data.NewJWTIssuer(bootstrap)
	usecase := captcha.NewUsecase()
	authUsecase := auth.NewUsecase(repo, permissionRepo, tokenIssuer, usecase)
	service := auth2.NewService(authUsecase, usecase)
	userUsecase := user2.NewUsecase(repo)
	userService := user3.NewService(userUsecase)
	roleRepo := role.NewRepo(dataData)
	roleUsecase := role2.NewUsecase(roleRepo)
	roleService := role3.NewService(roleUsecase)
	permissionUsecase := permission2.NewUsecase(permissionRepo)
	permissionService := permission3.NewService(permissionUsecase)
	httpServer := server.NewHTTPServer(bootstrap, service, userService, roleService, permissionService)
	return httpServer, func() {
		cleanup()
	}, nil
}

// wire.go:

var bizSet = wire.NewSet(user2.NewUsecase, role2.NewUsecase, permission2.NewUsecase, captcha.NewUsecase, auth.NewUsecase, wire.Bind(new(auth.CaptchaVerifier), new(*captcha.Usecase)))

var dataRepoSet = wire.NewSet(data.NewData, data.NewJWTIssuer, user.NewRepo, role.NewRepo, permission.NewRepo, wire.Bind(new(auth.UserReader), new(user2.Repo)), wire.Bind(new(auth.PermissionReader), new(permission2.Repo)))

var serviceSet = wire.NewSet(auth2.NewService, user3.NewService, role3.NewService, permission3.NewService)

var providerSet = wire.NewSet(bizSet, dataRepoSet, serviceSet, ProvideConfig, server.NewHTTPServer)
